apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eda-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - configmaps
      - secrets
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["cilium.io"]
    resources:
      - ciliumnetworkpolicies
      - ciliumclusterwidenetworkpolicies
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources:
      - nodes/proxy
      - nodes/stats
      - nodes/metrics
      - nodes/exec
    verbs: ["get", "create", "delete", "patch", "update"]
