---
- name: Falco Webhook Rule
  hosts: localhost
  sources:
    - name: falco-webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /falco
  rules:
    - name: Detect Sensitive File Read
      condition: event.payload.rule == "Read sensitive file untrusted"
      action:
        - debug:  # 🔍 Logs the incoming event in EDA logs for better visibility
            msg: "Received event payload: {{ event }}"
        - run_job_template:
            name: "Respond to Sensitive File Read"
            organization: "Default"
            extra_vars:
              eda_event: "{{ event }}"
