---
- name: Falco Webhook Rule
  hosts: localhost
  sources:
    - name: falco-webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /falco
  rules:
    - name: Detect Sensitive File Read
      condition: event.payload.rule == "Read sensitive file untrusted"
      action:
        run_job_template:
          name: "Respond to Sensitive File Read"
          organization: "Default"
          extra_vars:
            eda_event:
              payload: "{{ event.payload }}"
              meta: "{{ event.meta }}"
