apiVersion: v1
data:
  nginx_default_conf_template: "events {\n    worker_connections 1024;\n}\nhttp {\n
    \   map $http_x_forwarded_proto $remote_scheme {\n        default $http_x_forwarded_proto;\n
    \       ''      $scheme;\n    }\n\n    include mime.types;\n    types {\n        application/manifest+json
    webmanifest;\n    }\n    server {\n        listen 8080;\n                    listen
    [::]:8080;\n        \n        server_name _;\n        server_tokens off;\n\n        access_log
    off;\n        # error_log off;\n\n        autoindex off;\n\n        include mime.types;\n
    \       types {\n            application/manifest+json webmanifest;\n        }\n\n
    \       sendfile on;\n\n        root /usr/share/nginx/html;\n\n        location
    ~ ^/api/eda {\n            proxy_pass http://eda-demo-api:8000;\n            proxy_set_header
    Origin http://eda-demo-api:8000;\n            proxy_set_header Host $http_host;\n
    \           proxy_set_header X-Forwarded-Proto $remote_scheme;\n            proxy_set_header
    X-Forwarded-Port $server_port;\n            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \       }\n\n        location ~* \\.(json|woff|woff2|jpe?g|png|gif|ico|svg|css|js)$
    {\n            add_header Cache-Control \"public, max-age=31536000, s-maxage=31536000,
    immutable\";\n            try_files $uri =404;\n            gzip_static on;\n
    \       }\n\n        location / {\n            autoindex off;\n            expires
    off;\n            add_header Cache-Control \"public, max-age=0, s-maxage=0, must-revalidate\"
    always;\n            try_files $uri $uri/ /index.html =404;\n        }\n    }\n
    \ }\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"nginx_default_conf_template":"events
      {\n    worker_connections 1024;\n}\nhttp {\n    map $http_x_forwarded_proto
      $remote_scheme {\n        default $http_x_forwarded_proto;\n        ''''      $scheme;\n    }\n\n    include
      mime.types;\n    types {\n        application/manifest+json webmanifest;\n    }\n    server
      {\n        listen 8080;\n                    listen [::]:8080;\n        \n        server_name
      _;\n        server_tokens off;\n\n        access_log off;\n        # error_log
      off;\n\n        autoindex off;\n\n        include mime.types;\n        types
      {\n            application/manifest+json webmanifest;\n        }\n\n        sendfile
      on;\n\n        root /usr/share/nginx/html;\n\n        location ~ ^/api/eda {\n            proxy_pass
      http://eda-demo-api:8000;\n            proxy_set_header Origin http://eda-demo-api:8000;\n            proxy_set_header
      Host $http_host;\n            proxy_set_header X-Forwarded-Proto $remote_scheme;\n            proxy_set_header
      X-Forwarded-Port $server_port;\n            proxy_set_header X-Forwarded-For
      $proxy_add_x_forwarded_for;\n        }\n\n        location ~* \\.(json|woff|woff2|jpe?g|png|gif|ico|svg|css|js)$
      {\n            add_header Cache-Control \"public, max-age=31536000, s-maxage=31536000,
      immutable\";\n            try_files $uri =404;\n            gzip_static on;\n        }\n\n        location
      / {\n            autoindex off;\n            expires off;\n            add_header
      Cache-Control \"public, max-age=0, s-maxage=0, must-revalidate\" always;\n            try_files
      $uri $uri/ /index.html =404;\n        }\n    }\n  }\n"},"kind":"ConfigMap","metadata":{"labels":{"app.kubernetes.io/managed-by":"eda-operator","app.kubernetes.io/name":"eda-demo","app.kubernetes.io/operator-version":"","app.kubernetes.io/part-of":"eda-demo"},"name":"eda-demo-eda-configmap","namespace":"eda"}}'
  creationTimestamp: "2025-03-14T23:18:31Z"
  labels:
    app.kubernetes.io/managed-by: eda-operator
    app.kubernetes.io/name: eda-demo
    app.kubernetes.io/operator-version: ""
    app.kubernetes.io/part-of: eda-demo
  name: eda-demo-eda-configmap
  namespace: eda
  ownerReferences:
  - apiVersion: eda.ansible.com/v1alpha1
    kind: EDA
    name: eda-demo
    uid: 4045fc6e-a4d5-4fda-8fd5-ebb49c8995e1
  resourceVersion: "383440"
  uid: 4ba75b51-d14c-40a7-8075-51bc6dddf604
