apiVersion: v1
data:
  nginx_event_stream_default_conf_template: |
    events {
        worker_connections 1024;
    }
    http {
        map $http_x_forwarded_proto $remote_scheme {
            default $http_x_forwarded_proto;
            ''      $scheme;
        }

        include mime.types;
        types {
            application/manifest+json webmanifest;
        }

        upstream eda-api-event-stream-backend {
            server 127.0.0.1:8002;
        }

        server {
            listen 8000;

            location / {
                proxy_pass              http://eda-api-event-stream-backend/;
                proxy_set_header        Host $host:$server_port;
                proxy_set_header        X-Forwarded-Proto $scheme;
                proxy_set_header        X-Forwarded-Host $host;
                proxy_set_header        X-Forwarded-Port $server_port;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"nginx_event_stream_default_conf_template":"events
      {\n    worker_connections 1024;\n}\nhttp {\n    map $http_x_forwarded_proto
      $remote_scheme {\n        default $http_x_forwarded_proto;\n        ''''      $scheme;\n    }\n\n    include
      mime.types;\n    types {\n        application/manifest+json webmanifest;\n    }\n\n    upstream
      eda-api-event-stream-backend {\n        server 127.0.0.1:8002;\n    }\n\n    server
      {\n        listen 8000;\n\n        location / {\n            proxy_pass              http://eda-api-event-stream-backend/;\n            proxy_set_header        Host
      $host:$server_port;\n            proxy_set_header        X-Forwarded-Proto $scheme;\n            proxy_set_header        X-Forwarded-Host
      $host;\n            proxy_set_header        X-Forwarded-Port $server_port;\n            proxy_set_header        X-Forwarded-For
      $proxy_add_x_forwarded_for;\n        }\n    }\n}\n"},"kind":"ConfigMap","metadata":{"name":"eda-demo-nginx-event-stream-configmap","namespace":"eda"}}'
  creationTimestamp: "2025-03-14T23:18:40Z"
  name: eda-demo-nginx-event-stream-configmap
  namespace: eda
  ownerReferences:
  - apiVersion: eda.ansible.com/v1alpha1
    kind: EDA
    name: eda-demo
    uid: 4045fc6e-a4d5-4fda-8fd5-ebb49c8995e1
  resourceVersion: "383629"
  uid: 82fe5c41-d305-4f97-8eb1-5ecbc9a0fb7e
